Repository pyensemble/wildwood, pull requests merged in 2021-05, with the labels that each got.

#54 There is a mistake in the way we test that a split don't lead to childs with no valid samples
  debug.py
  essai-biner.ipynb
  essai.py
  tests/dataset-small-classification.csv.gz
  tests/dataset-small-regression.csv.gz
  tests/test_core.py
  tests/test_dataset.py
  tests/test_forest.py
  wildwood/_grow.py
  wildwood/_node.py
  wildwood/_split.py
  wildwood/_tree.py
  wildwood/_tree_context.py
  wildwood/_utils.py
  wildwood/dataset/dataset.py
  wildwood/forest.py
Labels: WIP, bug

#56 Heatmap
  heatmap.ipynb
  wildwood/forest.py
  wildwood/tree.py
Labels: READY

#41 N trees experiment
  experiments/n_tree_experiment.py
  experiments/n_trees_experiment.ipynb
  wildwood/dataset/dataset.py
  wildwood/forest.py
Labels: READY

#57 Adds min_samples_split and min_samples_leaf options
  tests/test_core.py
  wildwood/_grow.py
  wildwood/_split.py
  wildwood/_tree_context.py
  wildwood/tree.py
Labels: READY, enhancement

#59 Minimal example for experiment (using hyperopt) on lgb
  .gitignore
  check_data.py
  experiments/experiment.py
  experiments/run_hyperopt_classfiers.py
  wildwood/datasets/loaders.py
Labels: READY

#61 Add test for data loaders, fix datapath in default_cb and other fix in loaders
  pyproject.toml
  tests/test_data_loader.py
  wildwood/datasets/_higgs.py
  wildwood/datasets/_internet.py
  wildwood/datasets/_kick.py
  wildwood/datasets/dataset.py
  wildwood/datasets/loaders.py
Labels: READY, bug

#58 Split order new
  essai-biner.ipynb
  tests/test_core.py
  tests/test_forest.py
  wildwood/_split.py
  wildwood/_tree.py
  wildwood/_tree_context.py
  wildwood/_utils.py
  wildwood/forest.py
  wildwood/plot.py
  wildwood/tree.py
Labels: READY
