Repository pyensemble/wildwood, pull requests merged in 2021-04, with the labels that each got.

#20 Adds sample_weights and deal with class_weight option
  tests/test_forest.py
  wildwood/_grow.py
  wildwood/_node.py
  wildwood/_tree.py
  wildwood/_utils.py
  wildwood/forest.py
Labels: WIP, enhancement

#51 Adds option multiclass="ovr" with "multinomial" for one-versus rest training
  debug.py
  essai-biner.ipynb
  essai.py
  experiments/wildwood_classifier.py
  tests/test_forest.py
  wildwood/forest.py
Labels: enhancement

#55 ovr fix
  wildwood/forest.py
Labels: READY
