Repository pyensemble/wildwood, pull requests merged in 2021-09, with the labels that each got.

#73 First version of Encoder
  .travis.yml
  check_encoder.py
  essai-biner.ipynb
  essai.py
  main.py
  tests/test_dataset.py
  tests/test_encoder.py
  wildwood/_utils.py
  wildwood/preprocessing/__init__.py
  wildwood/preprocessing/_binning.py
  wildwood/preprocessing/dataset.py
  wildwood/preprocessing/encoder.py
Labels: enhancement, READY

#74 Add support for Entropy criterion
  check_cat.py
  tests/test_core.py
  tests/test_forest.py
  wildwood/_impurity.py
  wildwood/_split.py
  wildwood/_tree_context.py
  wildwood/_utils.py
  wildwood/forest.py
  wildwood/tree.py
Labels: enhancement, READY

#82 First version of the documentation
  docs/_static/alabaster.css
  docs/api.md
  docs/biblio.bib
  docs/conf.py
  docs/experiments.md
  docs/images/iterations.pdf
  docs/images/logo.png
  docs/images/playground.png
  docs/index.md
  docs/index.rst
  docs/requirements.txt
  docs/searchindex.js
  docs/wildwood.md
  wildwood/forest.py
Labels: documentation

#88 Cleaning of docstrings, documentation and
  .travis.yml
  README.md
  docs/api.md
  docs/conf.py
  docs/experiments.md
  examples/playground_tree_regression.py
  plot_signals_weighted_depth.py
  tests/test_data_loader.py
  tests/test_forest.py
  wildwood/datasets/dataset.py
  wildwood/datasets/loaders.py
  wildwood/forest.py
Labels: documentation, enhancement
